/*
* LOVE: Totally Awesome 2D Gaming.
* Website: http://love.sourceforge.net
* Licence: ZLIB/libpng
* Copyright (c) 2006-2008 LOVE Development Team
*
* This file was AUTOGENERATED by swigfusion! Please
* do not edit this file manually.
* 
* @author Anders Ruud / swigfusion
* @date 2008-07-09
**/

// Function from SWIG which opens the module.
extern "C" {
    int luaopen_mod_system(lua_State * L);
}

namespace love_system
{

	// Pointer to the module-open function, just to make things prettier.
	int (*mod_open)(lua_State * s) = luaopen_mod_system;

} // love_system
