#!/bin/bash
echo Generating src/Makefile.am ...
cd src
echo 'SUBDIRS =
AUTOMAKE_OPTIONS = subdir-objects
AM_CPPFLAGS = -I/usr/include/freetype2  $(INCLUDE_LUA) -I/usr/include/SDL -Iliblove/include -Ibox2d/Include

# LÖVE executable
bin_PROGRAMS = love
love_LDFLAGS = -lfreetype -lGL -lGLU -lIL -lILU -lILUT -lphysfs -lSDL -lSDL_mixer
love_LDADD =

love_SOURCES = \ ' > Makefile.am
find . \( -iname "*.c" -o -iname "*.cpp" -o -iname "*.h" \) -exec echo '{}' \\ \; >> Makefile.am
cd ..
echo src/Makefile.am is updated!
