#!/bin/bash
echo Generating src/Makefile.am ...
cd src
echo 'SUBDIRS =
AUTOMAKE_OPTIONS = subdir-objects
AM_CPPFLAGS = -I/usr/include/freetype2  $(INCLUDE_LUA) -I/usr/include/SDL

# LÖVE executable
bin_PROGRAMS = love
#love_LDFLAGS =
#love_LDADD =

love_SOURCES = \' > Makefile.am.tmp
find . \( \( -iname "*.c" -o -iname "*.cpp" -o -iname "*.h" \) -a ! -iname "wsocket.*" \) -exec echo '{}' \\ \; >> Makefile.am.tmp
head -c -3 Makefile.am.tmp > Makefile.am
echo >> Makefile.am
cd ..
echo src/Makefile.am is updated! \^.^
