#!/bin/bash
echo Generating src/Makefile.am ...
cd src
echo 'SUBDIRS =
AUTOMAKE_OPTIONS = subdir-objects
AM_CPPFLAGS = -I/usr/include/freetype2  $(INCLUDE_LUA) -I/usr/include/SDL -Ilove/include -Ilove_box2d/Include

# LÖVE executable
bin_PROGRAMS = love
love_LDFLAGS = -lfreetype -lGL -lGLU -lIL -lphysfs -lSDL
love_LDADD =

love_SOURCES = \' > Makefile.am
find . \( \( -iname "*.c" -o -iname "*.cpp" -o -iname "*.h" \) -a ! -iname "wsocket.*" \) -exec echo '{}' \\ \; >> Makefile.am
cd ..
echo src/Makefile.am is updated! Please remove the trailing backslash before compiling. ^.^
