#!/bin/bash
if [ -z "$2" ]; then
	echo "Syntax:  ./make-package <package> <version>"
	echo "Example: ./make-package deb 0.1.1"
	exit 0
fi
if [ "$1" == "deb" ]; then
	cd ../../
	make
	strip love
	cd platform/unix/
	mkdir deb
	mkdir deb/DEBIAN
	sed "s/%VERSION%/$2/" < debian > deb/DEBIAN/control
	mkdir deb/usr
	mkdir deb/usr/bin
	ln ../../love deb/usr/bin/love
	dpkg -b deb love-$2.deb
	rm -rf deb
else
	echo "Unknown package type: $1"
	echo "Valid types: deb"
fi
