/*
* LOVE: Totally Awesome 2D Gaming.
* Website: http://love.sourceforge.net
* Licence: ZLIB/libpng
* Copyright (c) 2006-2008 LOVE Development Team
*
* This file was AUTOGENERATED by swigfusion! Please
* do not edit this file manually.
* 
* @author Anders Ruud / swigfusion
* @date 2008-09-07
**/

#ifndef LOVE_MOD_FUSION_SDLKEYBOARD_H
#define LOVE_MOD_FUSION_SDLKEYBOARD_H

// Boost
#include <boost/shared_ptr.hpp>


// Function from SWIG which opens the module.
extern "C" {
    int luaopen_mod_sdlkeyboard(lua_State * L);
}

namespace love_sdlkeyboard
{

} // love_sdlkeyboard

#endif
