swig.exe -nodefaultctor -lua -c++ -o "..\..\src\chipmunk\mod_chipmunk.cpp" "..\..\src\chipmunk\mod_chipmunk.i"
swig.exe -nodefaultctor -lua -c++ -o "..\..\src\opengl\mod_opengl.cpp" "..\..\src\opengl\mod_opengl.i"
swig.exe -nodefaultctor -lua -c++ -o "..\..\src\physfs\mod_physfs.cpp" "..\..\src\physfs\mod_physfs.i"
swig.exe -nodefaultctor -lua -c++ -o "..\..\src\sdlkeyboard\mod_sdlkeyboard.cpp" "..\..\src\sdlkeyboard\mod_sdlkeyboard.i"
swig.exe -nodefaultctor -lua -c++ -o "..\..\src\sdlmixer\mod_sdlmixer.cpp" "..\..\src\sdlmixer\mod_sdlmixer.i"
swig.exe -nodefaultctor -lua -c++ -o "..\..\src\sdlmouse\mod_sdlmouse.cpp" "..\..\src\sdlmouse\mod_sdlmouse.i"
swig.exe -nodefaultctor -lua -c++ -o "..\..\src\sdltimer\mod_sdltimer.cpp" "..\..\src\sdltimer\mod_sdltimer.i"