/*
* LOVE: Totally Awesome 2D Gaming.
* Website: http://love.sourceforge.net
* Licence: ZLIB/libpng
* Copyright (c) 2006-2008 LOVE Development Team
*
* This file was AUTOGENERATED by swigfusion! Please
* do not edit this file manually.
* 
* @author Anders Ruud / swigfusion
* @date 2008-07-09
**/

// Function from SWIG which opens the module.
extern "C" {
    int luaopen_mod_chipmunk(lua_State * L);
}

// Types found:
// SegmentShape (SWIGTYPE_p_boost__shared_ptrT_love_chipmunk__SegmentShape_t)
// PolygonShape (SWIGTYPE_p_boost__shared_ptrT_love_chipmunk__PolygonShape_t)
// Vector (SWIGTYPE_p_boost__shared_ptrT_love_chipmunk__Vector_t)
// Space (SWIGTYPE_p_boost__shared_ptrT_love_chipmunk__Space_t)
// Shape (SWIGTYPE_p_boost__shared_ptrT_love_chipmunk__Shape_t)
// Body (SWIGTYPE_p_boost__shared_ptrT_love_chipmunk__Body_t)

namespace love_chipmunk
{

	// Pointer to the module-open function, just to make things prettier.
	int (*mod_open)(lua_State * s) = luaopen_mod_chipmunk;

	bool mod_is_segmentshape(lua_State * L, int idx);
	pSegmentShape mod_to_segmentshape(lua_State * L, int idx);
	void mod_push_segmentshape(lua_State * L, pSegmentShape segmentshape);

	bool mod_is_polygonshape(lua_State * L, int idx);
	pPolygonShape mod_to_polygonshape(lua_State * L, int idx);
	void mod_push_polygonshape(lua_State * L, pPolygonShape polygonshape);

	bool mod_is_vector(lua_State * L, int idx);
	pVector mod_to_vector(lua_State * L, int idx);
	void mod_push_vector(lua_State * L, pVector vector);

	bool mod_is_space(lua_State * L, int idx);
	pSpace mod_to_space(lua_State * L, int idx);
	void mod_push_space(lua_State * L, pSpace space);

	bool mod_is_shape(lua_State * L, int idx);
	pShape mod_to_shape(lua_State * L, int idx);
	void mod_push_shape(lua_State * L, pShape shape);

	bool mod_is_body(lua_State * L, int idx);
	pBody mod_to_body(lua_State * L, int idx);
	void mod_push_body(lua_State * L, pBody body);

} // love_chipmunk
