/**
* @file love_script_types.h
* @brief Contains generated types from SWIG.
* @date 2006-11-19
* @author AUTO-LOVE
* THIS FILE IS GENERATED AUTOMAGICALLY.
* DO NOT TOUCH THIS FILE.
**/

#ifndef LOVE_SCRIPT_TYPES_H
#define LOVE_SCRIPT_TYPES_H

enum script_types
{
	script_type_boost__shared_ptrTlove__AbstractColor_t = 0,
	script_type_boost__shared_ptrTlove__AbstractFont_t = 1,
	script_type_boost__shared_ptrTlove__AbstractImage_t = 2,
	script_type_love__DisplayMode = 3,
	script_type_pEvent = 4,
	script_type_p_GLuint = 5,
	script_type_p_GUIList = 6,
	script_type_p_ILuint = 7,
	script_type_p_LoadListener = 8,
	script_type_p_Matrix = 9,
	script_type_p_Sprite = 10,
	script_type_p_boost__shared_ptrTlove__AbstractColor_t = 11,
	script_type_p_boost__shared_ptrTlove__AbstractDisplay_t = 12,
	script_type_p_boost__shared_ptrTlove__AbstractEntity_t = 13,
	script_type_p_boost__shared_ptrTlove__AbstractFont_t = 14,
	script_type_p_boost__shared_ptrTlove__AbstractGraphics_t = 15,
	script_type_p_boost__shared_ptrTlove__AbstractImage_t = 16,
	script_type_p_boost__shared_ptrTlove__AbstractMusic_t = 17,
	script_type_p_boost__shared_ptrTlove__AbstractSound_t = 18,
	script_type_p_boost__shared_ptrTlove__AbstractState_t = 19,
	script_type_p_boost__shared_ptrTlove__ActorState_t = 20,
	script_type_p_boost__shared_ptrTlove__Actor_t = 21,
	script_type_p_boost__shared_ptrTlove__Bezier_t = 22,
	script_type_p_boost__shared_ptrTlove__Button_t = 23,
	script_type_p_boost__shared_ptrTlove__Color_t = 24,
	script_type_p_boost__shared_ptrTlove__DisplayMode_t = 25,
	script_type_p_boost__shared_ptrTlove__DropDown_t = 26,
	script_type_p_boost__shared_ptrTlove__Entity_t = 27,
	script_type_p_boost__shared_ptrTlove__Font_t = 28,
	script_type_p_boost__shared_ptrTlove__FrameAnimation_t = 29,
	script_type_p_boost__shared_ptrTlove__Keyboard_t = 30,
	script_type_p_boost__shared_ptrTlove__Label_t = 31,
	script_type_p_boost__shared_ptrTlove__Loadable_t = 32,
	script_type_p_boost__shared_ptrTlove__LuaGL_t = 33,
	script_type_p_boost__shared_ptrTlove__Menu_t = 34,
	script_type_p_boost__shared_ptrTlove__Mouse_t = 35,
	script_type_p_boost__shared_ptrTlove__MultilineLabel_t = 36,
	script_type_p_boost__shared_ptrTlove__ObjectFactory_t = 37,
	script_type_p_boost__shared_ptrTlove__Object_t = 38,
	script_type_p_boost__shared_ptrTlove__ParticleSystem_t = 39,
	script_type_p_boost__shared_ptrTlove__Sprite_t = 40,
	script_type_p_boost__shared_ptrTlove__TextField_t = 41,
	script_type_p_boost__shared_ptrTlove__Text_t = 42,
	script_type_p_boost__shared_ptrTlove__Timer_t = 43,
	script_type_p_boost__shared_ptrTlove__Vector_t = 44,
	script_type_p_boost__shared_ptrTlove__VisualEntity_t = 45,
	script_type_p_gcn__Graphics = 46,
	script_type_p_int = 47,
	script_type_p_listTlove__particle_t = 48,
	script_type_p_love__AbstractColor = 49,
	script_type_p_love__AbstractDisplay = 50,
	script_type_p_love__AbstractEntity = 51,
	script_type_p_love__AbstractFile = 52,
	script_type_p_love__AbstractFont = 53,
	script_type_p_love__AbstractGraphics = 54,
	script_type_p_love__AbstractImage = 55,
	script_type_p_love__AbstractMusic = 56,
	script_type_p_love__AbstractSound = 57,
	script_type_p_love__AbstractState = 58,
	script_type_p_love__Actor = 59,
	script_type_p_love__ActorState = 60,
	script_type_p_love__Bezier = 61,
	script_type_p_love__Button = 62,
	script_type_p_love__Color = 63,
	script_type_p_love__ContainerTlove__Sprite_t = 64,
	script_type_p_love__DisplayMode = 65,
	script_type_p_love__DropDown = 66,
	script_type_p_love__Entity = 67,
	script_type_p_love__Font = 68,
	script_type_p_love__FrameAnimation = 69,
	script_type_p_love__KeyListener = 70,
	script_type_p_love__Keyboard = 71,
	script_type_p_love__Label = 72,
	script_type_p_love__Listener = 73,
	script_type_p_love__Loadable = 74,
	script_type_p_love__LuaGL = 75,
	script_type_p_love__LuaGame = 76,
	script_type_p_love__Menu = 77,
	script_type_p_love__Mouse = 78,
	script_type_p_love__MouseListener = 79,
	script_type_p_love__MultilineLabel = 80,
	script_type_p_love__Object = 81,
	script_type_p_love__ObjectFactory = 82,
	script_type_p_love__Padded = 83,
	script_type_p_love__ParticleSystem = 84,
	script_type_p_love__Renderable = 85,
	script_type_p_love__Sprite = 86,
	script_type_p_love__Text = 87,
	script_type_p_love__TextField = 88,
	script_type_p_love__Timer = 89,
	script_type_p_love__Updateable = 90,
	script_type_p_love__Vector = 91,
	script_type_p_love__VisualEntity = 92,
	script_type_p_love__interval = 93,
	script_type_p_love__la = 94,
	script_type_p_love__particle = 95,
	script_type_p_love__renderinfo = 96,
	script_type_p_love__rgb = 97,
	script_type_p_love__rgba = 98,
	script_type_p_lua_State = 99,
	script_type_p_pAnimatedColor = 100,
	script_type_p_pEvent = 101,
	script_type_p_std__string = 102,
	script_type_p_string = 103,
	script_type_p_vectorTlove__Vector_t = 104,
	script_type_string = 105
};

#endif
