/**
* @file love_types.h
* @author Anders Ruud
* @date 2006-08-02
* @brief Contains identifiers for all types.
**/

#ifndef LOVE_TYPES_H
#define LOVE_TYPES_H


namespace love 
{

	enum love_types
	{
		LOVE_TYPE_OBJECT, 
		LOVE_TYPE_ENTITY, 
		LOVE_TYPE_ABSTRACT_ENTITY, 
		LOVE_TYPE_ACTOR,
		LOVE_TYPE_ACTOR_STATE,
		LOVE_TYPE_ANIMATION,
		LOVE_TYPE_ASTAR, 
		LOVE_TYPE_ATTRACTOR, 
		LOVE_TYPE_BODY, 
		LOVE_TYPE_CELL, 
		LOVE_TYPE_CIRCLE, 
		LOVE_TYPE_COLLISIONDETECTOR, 
		LOVE_TYPE_COLLISION_EVENT,
		LOVE_TYPE_COLOR, 
		LOVE_TYPE_COMPOSITE_BODY,
		LOVE_TYPE_CONTAINER,
		LOVE_TYPE_CORE,
		LOVE_TYPE_EVENT,
		LOVE_TYPE_GUI_EVENT,
		LOVE_TYPE_FONT,
		LOVE_TYPE_FRAME_ANIMATION,
		LOVE_TYPE_GAME,
		LOVE_TYPE_GAME_CONTROL_EVENT,
		LOVE_TYPE_GAME_STATE,
		LOVE_TYPE_GRADIENT_COLOR,
		LOVE_TYPE_GRID,
		LOVE_TYPE_HIERARCHY_GRID,
		LOVE_TYPE_IMAGE,
		LOVE_TYPE_KEYBOARD,
		LOVE_TYPE_LAYER,
		LOVE_TYPE_LINE,
		LOVE_TYPE_LOADER,
		LOVE_TYPE_MAP,
		LOVE_TYPE_MATRIX,
		LOVE_TYPE_MESSAGE_EVENT,
		LOVE_TYPE_NEW_FONT,
		LOVE_TYPE_OBJECT_MANAGER,
		LOVE_TYPE_PARTICLE,
		LOVE_TYPE_PARTICLE_EMITTER,
		LOVE_TYPE_PATH,
		LOVE_TYPE_POINT,
		LOVE_TYPE_POINT_MASS,
		LOVE_TYPE_POLYGON,
		LOVE_TYPE_RECTANGLE,
		LOVE_TYPE_SCRIPTABLE_ACTOR_STATE,
		LOVE_TYPE_SCRIPTABLE_PARTICLE,
		LOVE_TYPE_SDL_TIMER,
		LOVE_TYPE_SHAPE,
		LOVE_TYPE_SOUND,
		LOVE_TYPE_SPLASH_SCREEN,
		LOVE_TYPE_SPRITE,
		LOVE_TYPE_STATE_ANIMATION,
		LOVE_TYPE_TEXT,
		LOVE_TYPE_TILE,
		LOVE_TYPE_TILE_LAYER,
		LOVE_TYPE_TILESET,
		LOVE_TYPE_TIMER,
		LOVE_TYPE_VECTOR,
		LOVE_TYPE_VEXTOR,
		LOVE_TYPE_VIEWPORT,
		LOVE_TYPE_WINDOW,
		LOVE_TYPE_LUA_GAME,
		LOVE_TYPE_LUA_GAMESTATE,
		LOVE_TYPE_MOUSE,
		LOVE_TYPE_LUAGL,
		LOVE_TYPE_DISPLAY_MODE,
		LOVE_TYPE_VISUAL_ENTITY,
		LOVE_NUM_TYPES

	};
}

#endif
