/**
* @file love_script_types.h
* @brief Contains generated types from SWIG.
* @date 2006-11-19
* @author AUTO-LOVE
* THIS FILE IS GENERATED AUTOMAGICALLY.
* DO NOT TOUCH THIS FILE.
**/

#ifndef LOVE_SCRIPT_TYPES_H
#define LOVE_SCRIPT_TYPES_H

enum script_types
{
	script_type_boost__shared_ptrTlove__AbstractImage_t = 0,
	script_type_boost__shared_ptrTlove__Font_t = 1,
	script_type_pEvent = 2,
	script_type_p_GLuint = 3,
	script_type_p_ILuint = 4,
	script_type_p_LoadListener = 5,
	script_type_p_Matrix = 6,
	script_type_p_ParticleEmitter = 7,
	script_type_p_Sprite = 8,
	script_type_p_boost__shared_ptrTlove__AbstractColor_t = 9,
	script_type_p_boost__shared_ptrTlove__AbstractEntity_t = 10,
	script_type_p_boost__shared_ptrTlove__AbstractFont_t = 11,
	script_type_p_boost__shared_ptrTlove__AbstractGraphics_t = 12,
	script_type_p_boost__shared_ptrTlove__AbstractImage_t = 13,
	script_type_p_boost__shared_ptrTlove__AbstractMusic_t = 14,
	script_type_p_boost__shared_ptrTlove__AbstractSound_t = 15,
	script_type_p_boost__shared_ptrTlove__AbstractState_t = 16,
	script_type_p_boost__shared_ptrTlove__ActorState_t = 17,
	script_type_p_boost__shared_ptrTlove__Actor_t = 18,
	script_type_p_boost__shared_ptrTlove__Bezier_t = 19,
	script_type_p_boost__shared_ptrTlove__Color_t = 20,
	script_type_p_boost__shared_ptrTlove__DisplayMode_t = 21,
	script_type_p_boost__shared_ptrTlove__Entity_t = 22,
	script_type_p_boost__shared_ptrTlove__Font_t = 23,
	script_type_p_boost__shared_ptrTlove__FrameAnimation_t = 24,
	script_type_p_boost__shared_ptrTlove__Keyboard_t = 25,
	script_type_p_boost__shared_ptrTlove__Loadable_t = 26,
	script_type_p_boost__shared_ptrTlove__LuaGL_t = 27,
	script_type_p_boost__shared_ptrTlove__LuaGame_t = 28,
	script_type_p_boost__shared_ptrTlove__Mouse_t = 29,
	script_type_p_boost__shared_ptrTlove__ObjectFactory_t = 30,
	script_type_p_boost__shared_ptrTlove__Object_t = 31,
	script_type_p_boost__shared_ptrTlove__ParticleSystem_t = 32,
	script_type_p_boost__shared_ptrTlove__Sprite_t = 33,
	script_type_p_boost__shared_ptrTlove__Text_t = 34,
	script_type_p_boost__shared_ptrTlove__Timer_t = 35,
	script_type_p_boost__shared_ptrTlove__Vector_t = 36,
	script_type_p_boost__shared_ptrTlove__VisualEntity_t = 37,
	script_type_p_int = 38,
	script_type_p_love__AbstractColor = 39,
	script_type_p_love__AbstractDisplay = 40,
	script_type_p_love__AbstractEntity = 41,
	script_type_p_love__AbstractFile = 42,
	script_type_p_love__AbstractFont = 43,
	script_type_p_love__AbstractGraphics = 44,
	script_type_p_love__AbstractImage = 45,
	script_type_p_love__AbstractMusic = 46,
	script_type_p_love__AbstractSound = 47,
	script_type_p_love__AbstractState = 48,
	script_type_p_love__Actor = 49,
	script_type_p_love__ActorState = 50,
	script_type_p_love__Bezier = 51,
	script_type_p_love__Color = 52,
	script_type_p_love__ContainerTlove__Sprite_t = 53,
	script_type_p_love__DisplayMode = 54,
	script_type_p_love__Entity = 55,
	script_type_p_love__Font = 56,
	script_type_p_love__FrameAnimation = 57,
	script_type_p_love__KeyListener = 58,
	script_type_p_love__Keyboard = 59,
	script_type_p_love__Listener = 60,
	script_type_p_love__Loadable = 61,
	script_type_p_love__LuaGL = 62,
	script_type_p_love__LuaGame = 63,
	script_type_p_love__Mouse = 64,
	script_type_p_love__MouseListener = 65,
	script_type_p_love__Object = 66,
	script_type_p_love__ObjectFactory = 67,
	script_type_p_love__ParticleSystem = 68,
	script_type_p_love__Renderable = 69,
	script_type_p_love__Sprite = 70,
	script_type_p_love__Text = 71,
	script_type_p_love__Timer = 72,
	script_type_p_love__Updateable = 73,
	script_type_p_love__Vector = 74,
	script_type_p_love__VisualEntity = 75,
	script_type_p_love__interval = 76,
	script_type_p_love__la = 77,
	script_type_p_love__particle = 78,
	script_type_p_love__renderinfo = 79,
	script_type_p_love__rgb = 80,
	script_type_p_love__rgba = 81,
	script_type_p_lua_State = 82,
	script_type_p_pEvent = 83,
	script_type_p_std__string = 84,
	script_type_p_string = 85,
	script_type_p_vectorTlove__Vector_t = 86,
	script_type_string = 87
};

#endif
