/**
* @file love_script_types.h
* @brief Contains generated types from SWIG.
* @date 2006-11-19
* @author AUTO-LOVE
* THIS FILE IS GENERATED AUTOMAGICALLY.
* DO NOT TOUCH THIS FILE.
**/

#ifndef LOVE_SCRIPT_TYPES_H
#define LOVE_SCRIPT_TYPES_H

enum script_types
{
	script_type_pEvent = 0,
	script_type_p_Color = 1,
	script_type_p_GLuint = 2,
	script_type_p_ILuint = 3,
	script_type_p_LoadListener = 4,
	script_type_p_Matrix = 5,
	script_type_p_boost__shared_ptrTlove__AbstractColor_t = 6,
	script_type_p_boost__shared_ptrTlove__AbstractEntity_t = 7,
	script_type_p_boost__shared_ptrTlove__AbstractImage_t = 8,
	script_type_p_boost__shared_ptrTlove__AbstractMusic_t = 9,
	script_type_p_boost__shared_ptrTlove__AbstractSound_t = 10,
	script_type_p_boost__shared_ptrTlove__AbstractState_t = 11,
	script_type_p_boost__shared_ptrTlove__ActorState_t = 12,
	script_type_p_boost__shared_ptrTlove__Actor_t = 13,
	script_type_p_boost__shared_ptrTlove__DisplayMode_t = 14,
	script_type_p_boost__shared_ptrTlove__Entity_t = 15,
	script_type_p_boost__shared_ptrTlove__Font_t = 16,
	script_type_p_boost__shared_ptrTlove__FrameAnimation_t = 17,
	script_type_p_boost__shared_ptrTlove__Keyboard_t = 18,
	script_type_p_boost__shared_ptrTlove__Loadable_t = 19,
	script_type_p_boost__shared_ptrTlove__LuaGL_t = 20,
	script_type_p_boost__shared_ptrTlove__LuaGame_t = 21,
	script_type_p_boost__shared_ptrTlove__Mouse_t = 22,
	script_type_p_boost__shared_ptrTlove__Object_t = 23,
	script_type_p_boost__shared_ptrTlove__ParticleEmitter_t = 24,
	script_type_p_boost__shared_ptrTlove__ParticleSystem_t = 25,
	script_type_p_boost__shared_ptrTlove__Particle_t = 26,
	script_type_p_boost__shared_ptrTlove__ScriptableParticle_t = 27,
	script_type_p_boost__shared_ptrTlove__Sprite_t = 28,
	script_type_p_boost__shared_ptrTlove__Text_t = 29,
	script_type_p_boost__shared_ptrTlove__Timer_t = 30,
	script_type_p_boost__shared_ptrTlove__Vextor_t = 31,
	script_type_p_boost__shared_ptrTlove__VisualEntity_t = 32,
	script_type_p_int = 33,
	script_type_p_love__AbstractColor = 34,
	script_type_p_love__AbstractEntity = 35,
	script_type_p_love__AbstractFile = 36,
	script_type_p_love__AbstractImage = 37,
	script_type_p_love__AbstractMusic = 38,
	script_type_p_love__AbstractSound = 39,
	script_type_p_love__AbstractState = 40,
	script_type_p_love__Actor = 41,
	script_type_p_love__ActorState = 42,
	script_type_p_love__ContainerTColor_t = 43,
	script_type_p_love__ContainerTlove__Font_t = 44,
	script_type_p_love__ContainerTlove__Sprite_t = 45,
	script_type_p_love__DisplayMode = 46,
	script_type_p_love__Entity = 47,
	script_type_p_love__Font = 48,
	script_type_p_love__FrameAnimation = 49,
	script_type_p_love__KeyListener = 50,
	script_type_p_love__Keyboard = 51,
	script_type_p_love__Listener = 52,
	script_type_p_love__Loadable = 53,
	script_type_p_love__LuaGL = 54,
	script_type_p_love__LuaGame = 55,
	script_type_p_love__Mouse = 56,
	script_type_p_love__MouseListener = 57,
	script_type_p_love__Object = 58,
	script_type_p_love__Particle = 59,
	script_type_p_love__ParticleEmitter = 60,
	script_type_p_love__ParticleSystem = 61,
	script_type_p_love__Renderable = 62,
	script_type_p_love__ScriptableActorState = 63,
	script_type_p_love__ScriptableParticle = 64,
	script_type_p_love__Sprite = 65,
	script_type_p_love__Text = 66,
	script_type_p_love__Timer = 67,
	script_type_p_love__Updateable = 68,
	script_type_p_love__Vextor = 69,
	script_type_p_love__VisualEntity = 70,
	script_type_p_love__interval = 71,
	script_type_p_love__la = 72,
	script_type_p_love__particle = 73,
	script_type_p_love__renderinfo = 74,
	script_type_p_love__rgb = 75,
	script_type_p_love__rgba = 76,
	script_type_p_lua_State = 77,
	script_type_p_pEvent = 78,
	script_type_p_std__string = 79,
	script_type_p_string = 80,
	script_type_string = 81
};

#endif
