/*
* LOVE: Totally Awesome 2D Gaming.
* Website: http://love.sourceforge.net
* Licence: ZLIB/libpng
* Copyright (c) 2006-2008 LOVE Development Team
*
* This file was AUTOGENERATED by swigfusion! Please
* do not edit this file manually.
* 
* @author Anders Ruud / swigfusion
* @date 2008-07-09
**/

// Function from SWIG which opens the module.
extern "C" {
    int luaopen_mod_opengl(lua_State * L);
}

// Types found:
// Sprite (SWIGTYPE_p_boost__shared_ptrT_love_opengl__Sprite_t)
// Image (SWIGTYPE_p_boost__shared_ptrT_love_opengl__Image_t)
// Animation (SWIGTYPE_p_boost__shared_ptrT_love_opengl__Animation_t)
// Color (SWIGTYPE_p_boost__shared_ptrT_love_opengl__Color_t)
// ParticleSystem (SWIGTYPE_p_boost__shared_ptrT_love_opengl__ParticleSystem_t)
// Font (SWIGTYPE_p_boost__shared_ptrT_love_opengl__Font_t)

// Fused: 
// Color:getRGB => _Color_getRGB

namespace love_opengl
{

	// Pointer to the module-open function, just to make things prettier.
	int (*mod_open)(lua_State * s) = luaopen_mod_opengl;

	bool mod_is_sprite(lua_State * L, int idx);
	pSprite mod_to_sprite(lua_State * L, int idx);
	void mod_push_sprite(lua_State * L, pSprite sprite);

	bool mod_is_image(lua_State * L, int idx);
	pImage mod_to_image(lua_State * L, int idx);
	void mod_push_image(lua_State * L, pImage image);

	bool mod_is_animation(lua_State * L, int idx);
	pAnimation mod_to_animation(lua_State * L, int idx);
	void mod_push_animation(lua_State * L, pAnimation animation);

	bool mod_is_color(lua_State * L, int idx);
	pColor mod_to_color(lua_State * L, int idx);
	void mod_push_color(lua_State * L, pColor color);

	bool mod_is_particlesystem(lua_State * L, int idx);
	pParticleSystem mod_to_particlesystem(lua_State * L, int idx);
	void mod_push_particlesystem(lua_State * L, pParticleSystem particlesystem);

	bool mod_is_font(lua_State * L, int idx);
	pFont mod_to_font(lua_State * L, int idx);
	void mod_push_font(lua_State * L, pFont font);

} // love_opengl
